# Generated by Django 2.2 on 2020-06-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('RES', 'Research'), ('VIS', 'Visit'), ('SCH', 'School'), ('CON', 'Conference'), ('COM', 'Competition')], max_length=3, null=True),
        ),
    ]
