# Generated by Django 2.2 on 2020-07-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('photo', models.ImageField(default='workshop_default.jpg', upload_to='workshop_pics')),
                ('when', models.DateTimeField()),
                ('where', models.CharField(max_length=500)),
                ('duration', models.TimeField()),
                ('cost', models.BigIntegerField()),
            ],
        ),
    ]
