# Generated by Django 2.2 on 2020-07-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_workshop_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='summary',
            field=models.TextField(default='New Workshop'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='duration',
            field=models.CharField(default='2 hrs', max_length=50),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='photo',
            field=models.ImageField(default='workshop_default.png', upload_to='workshop_pics'),
        ),
    ]
